### ISSUE TITLE
RFE: Day Hours begin 

### ISSUE THREAD

**Issue by nognkantoor** [forrestguice/NaturalHour#1]
Current options for setting the start of the day are:
* Sunrise;
* Civil Twilight;

Can you add Sunset to that list?  (Jewish Shabat begins at Sunset, and ends when three stars can be seen, after the following sunset. (OK, technically, the day begins begins with the sun is 16.1, 18, 19.8 degrees below the horizon, or 120, 96, or 72 minutes before the upper limb of the sun touches the horizon. Hours, however, are counted from when the upper limb touches the horizon.)

**Comment by forrestguice** [comment]
This sounds interesting. I've been reading more about this trying to understand the implications. 

I'm confused over the ways the clockface would be different than with the "sunrise" setting? If I understand correctly, the hours are still numbered 1-12 for daylight, and 1-12 for night, but for a given "day" the nighttime hours occur first, followed by daytime hours. However since the app isn't tracking which day it is (e.g. is it the 2nd day or 3rd day), and numbering 1-12 works for both definitions, I'm not sure about the specific differences the clockface would display. I guess if the numbering is actually supposed to be 1-24 this a lot more challenging, since on any given calendar date (before sunset), the numbering of the hours began sunset the date before.

Maybe this option is mislabeled or misleading and should be changed? Its supposed to define the boundary between the 12 daytime hours and nightime hours (and this seems the same thing with a "sunset" setting). I hadn't considered that it implied that days were numbered (and that the app tracked hour-1 of any given day).

**Comment by nognkantoor** [comment]
a) I closed the the other issue, since it was a duplicate of this one.  Not sure how/why I wrote it twice. :(

b) Sunrise implies the upper limb of the sun touching the horizon.  
Civil Twilight implies the sun is within 6 degrees below the horizon.
Sunset implies the upper limb of the sun touching the horizon.

Dusk is the start of the First Watch. 

Sunup, dawn, sunrise, and the upper limb of the rising sun touches the horizon are synonyms.  
Sundown, dusk, sunset and the upper limb of the setting sun touching the horizon are synonyms.

c) Shabbat is 25 hours long. The other days are 24 hours long.  The 25th hour starts when the upper limb of the sun touches the horizon, and ends when:
* You can physically see three widely separated stars in the sky; 
* Sun is 7.5 degrees below the horizon, or 42 minutes after sunset in Jerusalem;
* Sun is 8.5 degrees below the horizon;
* Sun is 8.75 degrees below the horizon. 50 Minutes after sunset for European latitudes, is a compromise, because most people can't calculate the position of the sun when it is below the horizon;
* Sun is 16.1 degrees below the horizon;
* Sun is 18.0 degrees below the horizon;
* Sun is 19.2 degrees below the horizon;
* 72 minutes after sunset. This covers virtually all possible scenarios south of 60 North, and north of 60 South.  (It might be 66 degrees or 70 degree instead of 60 degrees. The notes I made are unclear because they show both failures and successes at all of those latitudes.) Regardless, all calculations on when to pray, that rely on sunrise or sunset, will fail north of 60 North, and south of 60 South, at some point during the year.

The day after Shabbat has 24 hours, starting at sundown. The only exception is when one Shabbat follows another Shabbat, which can occur during the High Holy Days.  However, even there, the two days simultaneously. Hour 24.5 for day one and hour 0.5 for day 2. (IOW, people that need the 25th hour, can/will automatically make the necessary adjustments. The 25th hour always occurs during First Watch.)

This 25 hour religious day is not unlike the 30 hour nightclub day. Used by habitues, and either ignored or unknown by the rest of the world.

d) I'm looking at this from three perspectives:
* Swahili Time, which begins at sunrise.
* Jewish Time, which begins at sunset. This is when the date changes.
* Roman Time, which begins when the sun as at the nadir. This is when the date changes.

In terms of clock face:
* Swahili Time: The First Hour is when the sun rises.  Everything is numbered from then.
* Jewish Time: The First Hour is when the sun sets.  Everything is numbered from then.
* Roman Time: Everything is numbered from Sunset, then the numbering restarts at sunrise.

**Comment by forrestguice** [comment]
Thank you, this is really helpful.

So I guess something like
![1](https://user-images.githubusercontent.com/10246147/95692582-d25d3800-0bdb-11eb-917e-417063559b34.png)

I was thinking different numerals might be fun. Do you have an opinion on this?

Hebrew
![2](https://user-images.githubusercontent.com/10246147/95692622-08022100-0bdc-11eb-8793-877fa5ea03ff.png)

Attic
![3](https://user-images.githubusercontent.com/10246147/95692687-6e873f00-0bdc-11eb-9b3d-afff8e5d67c5.png)

**Comment by nognkantoor** [comment]
Those clock faces look good.
(This is when I wish I knew how to compile for Android.)

**Comment by forrestguice** [comment]
I've put a release build here; https://github.com/forrestguice/NaturalHour/releases

Its the first tagged release - its rough around the edges. I was procrastinating on this for a long time, and then basically forgot. It feels like I must fight perfectionist tendencies or nothing would ever be released.
