### ISSUE TITLE
General thoughts on the clockface

### ISSUE THREAD

**Issue by XanderLeaDaren** [forrestguice/NaturalHour#5]
Here are a few comments to improve the design, after using the app everyday of this week – thanks a lot for the app, again! 😉 

· I think an option to put midday on top (= the instant between VI and VII) would be a nice addition to the actual choice between 12:00 and 24:00
· I suggest to change the grey areas for twilights so they get more distinguishable. My tests: #1a1a1a (26/256), #333333 (51/256) and #4d4d4d (77/256), and changing the afternoon grey to #666666 (102/255)
· thanks for the option to choose days beginning at civil twilight. I didn’t know of this way before, and I agree it feels very natural.

I wonder how nice it would be to display a numeric/digital user-chosen current time (between mean / solar / system / suntimes) in the middle.

And, as a bonus question, how difficult would it be to have separate display settings for the app and the widget?

**Comment by forrestguice** [comment]
> an option to put midday on top 

Sounds interesting - it should be possible. So it basically has the same alignment as "apparent solar time" (which always centers noon), but instead rotates the inside of the dial (vs the outside) to account for timezone difference.

> grey areas for twilights

I'll give these values a try. Its worth mentioning that the latest includes a tool for changing colors while the app is running. It doesn't save or restore them though (they are lost when the app is closed). Its only intended to help experiment (and then make changes to the code). I want to provide a couple of good default appearances (with user-defined themes something to be added eventually).

> a numeric/digital user-chosen current time 

Sounds reasonable. I think its useful because the precision of a 24hr dial isn't so great (any increment smaller than 5min is hard to make out).

> separate display settings for the app and the widget

This is on the roadmap. Its definitely useful because it allows having multiple clockfaces side-by-side.

Its trivial for the widget to provide its own configuration activity, but I want to provide the same functionality already in Suntimes (location picker, timezone picker, etc), but without rewriting those solutions, or duplicating code. That's a challenge because the addon is technically a separate package (and its interaction with the main app a form of IPC). What I imagine is the addon widget having a configuration activity very similar to the one in Suntimes (ideally the exact same activity) but with the actual responsibility delegated to Suntimes. The goal being that any of these "addons" can add a widget without duplicating a bunch of code, and get the existing functionality "for free".

**Comment by XanderLeaDaren** [comment]
Thanks for letting us up to date with the development of this app.

I’m really amazed by the time you dedicate to share details on the process. 👌🏽

**Comment by forrestguice** [comment]
> with user-defined themes to be added eventually

Well this was the plan but 'eventually' turned out to be 'right away'. I've added user-defined colors - go nuts! It is implemented in a very generic way - it should be possible to scale this, or reuse this solution across projects (a candidate to replace the existing Suntimes theme system).

**Comment by XanderLeaDaren** [comment]
You did a lot of nice additions to edit the colours of the clock face, with a neat colour picker. 👌🏽 The light set looks good as a widget!

Thanks for adding the option to centre on solar noon, too.

I’ll be using the widget & app further more and letting you know in days to come. 😃
