### ISSUE TITLE
Testing the .apk - unable to install

### ISSUE THREAD

**Issue by XanderLeaDaren** [forrestguice/NaturalHour#6]
Hey there,
I’m not able, for a few builds now, to install the resulting .apk from the Actions runs Artifacts.

Whenever I try to install, the phone just says “Application not installed” without any further explanation.

The last version I was able to install is 0.1.0 (dc52f0d) [debug]
+ In case it’s needed to understand the issue: Suntimes 0.13.1 (4)

**Comment by forrestguice** [comment]
:\ That message looks familiar but I thought it was resolved with 1da8cd2a26e3336ae1a4ba19d0d687ccf43efcde

I got this message after adding adding a custom permission to the widget configuration activities. Every time I'd try to add a widget I'd see "Application not installed". It turns out by declaring the permission I was denying access to the launcher.

That was a few commits ago, but the latest build (f2b34c1) should have resolved it. This is a shot in the dark, but try uninstalling/reinstalling the app completely (vs installing over the previous version). I hope that's all it is. I'll take a closer look. So far all my installations have been through adb, so quite possible there's an issue here yet to be noticed.

**Comment by forrestguice** [comment]
Ok, I just gave this a try. It failed to install the latest (f2b34c1) over my previous copy. I get the "Application not installed" message, but with an additional line about conflicting signatures. However, the installation succeeds after removing the previous version. So now I'm optimistic its a side-effect of adding/removing the permission from the manifest.

btw, Suntimes v0.13.2 adds the ability reconfigure addon widgets; Settings -> Widgets should display them in the list. Making this work correctly was the point of messing around w/ the custom permission.

**Comment by forrestguice** [comment]
hrm. Actually.. These might be different errors (but the same vague message). I think it happens consistently when trying to install one (unsigned) debug build over another. It seems to be necessary to completely remove the previous package first (as a last resort `adb uninstall com.forrestguice.suntimes.naturalhour`).

**Comment by XanderLeaDaren** [comment]
You were right: removing the previous package and installing from scratch is the way to go: I got the last build working.

I admit I could have thought about it! 😅
